url: https://matthewjmay.github.io
baseurl: 

# Site settings
title: Cooke's Concrete
email: cookesconcrete@gmail.com
description: "Cooke's Concrete."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cookesconcrete
  - title: facebook
    url: https://www.facebook.com/cookesconcrete
  - title: instagram
    url: https://www.instagram.com/cookesconcrete

collections:
  projects:

project_order:
  - table1
  - bar1
  - table2
  - New Project
  - colored
  - matching-tables
  - bar2

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
