url: /cookesconcrete
baseurl: https://matthewjmay.github.io

# Site settings
title: Cooke's Concrete
email: cookesconcrete@gmail.com
description: "Cooke's Concrete."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cookesconcrete
  - title: facebook
    url: https://www.facebook.com/cookesconcrete
  - title: instagram
    url: https://www.instagram.com/cookesconcrete

collections:
  projects:
    order:
      - table1.md
      - bar1.md
      - table2.md
      - colored.md
      - matching-tables.md
      - table2.md
      - bar2.md

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock